### ISSUE TITLE
Change scope delimiter string

### ISSUE THREAD

**Issue by tpavlek** [laravel/passport#1008]
Currently passport uses a space as the default scope delimiter string, and it doesn't seem possible to change that?

This should be changeable, especially since Socialite uses commas as the default, leading to breakages in compatibility between the two.

**Comment by driesvints** [comment]
How does Socialite using comma's break Passport?

**Comment by matt-allan** [comment]
Not sure about the OP but I can see how that would be an issue.

Let's say you have two Laravel applications.  One of them ('server') runs the Passport server.  The other ('client') one uses the authorization code grant to allow users to login using the passport server.

On the client it's convenient to use Socialite to login - you can write a custom Socialite provider and then the login code is just `Socialite::driver('passport')->redirect()`.  However if you do this and you want to use scopes you have to override the `scopeSeparator` property because socialite tries to use `,` by default and passport uses ` `.

**Comment by tpavlek** [comment]
Yeah @matt-allan is exactly right here. Socialite tries to use commas, passport uses spaces (and can ONLY use spaces).

That's an incompatibility. Being able to change the scope separator addresses this incompatibility.

**Comment by driesvints** [comment]
Can you maybe whip up a small example app that would demonstrate how this works?

**Comment by driesvints** [comment]
Imo I don't think it's necessary to provide a setting for this. All the examples I've seen so far with OAuth2 are using spaces. If you can give a clear example why you need this this might be reconsidered.

I also think it's best that we change the default for Socialite to a space.
