### ISSUE TITLE
Testing: Request has authenticated user although no Auth header is present

### ISSUE THREAD

**Issue by romanzipp** [laravel/passport#1017]
- Passport Version: 7.2.2
- Laravel Version: 5.8.16
- PHP Version: 7.3.5

### Description:

We stumbled across an issue where the auth guard has a "cached" version of the authenticated user from the last valid request.

This issue occures, if a valid and authenticated request has been executed in the same phpunit test before.
The next requests will always be authenticated unless a manual verification of the request will be triggered on the Passport RequestGuard.

I'm not certain if this is an issue with Passport, Laravel or PHPUnit.

### Steps To Reproduce:

**[I've created a dedicated repository for issue: romanzipp/Laravel-Passport-Issue](https://github.com/romanzipp/Laravel-Passport-Issue)**

- Create a route that requires api authentication
- Execute an authenticated request in a PHPUnit test
- Execute a second unauthenticated request in the same test
- The second request will return HTTP 200 instead of expected 401

**Comment by driesvints** [comment]
You're performing two api requests in the same test run by putting the following in the `setUp` method which is run before a test method is run. That's why it's done in the same request and the authenticated state is still cached. Laravel doesn't supports running two HTTP requests in the same test method.

https://github.com/romanzipp/Laravel-Passport-Issue/blob/master/tests/Feature/AuthApiTest.php#L17-L20
