### ISSUE TITLE
table oauth_clients does not exists

### ISSUE THREAD

**Issue by BartReymenants** [laravel/passport#1025]
I have installed Passport without problems
but now I'm on the frontend quickstart there's an issue for creating new client/token
my users model uses a custom DB connection using the connection var in the user model and setup in the database config:

    protected $connection = 'customDBConnection';

though I'm not yet able to override the connection in the $clientModel (= Laravel\Passport\Client) since this model has not been published / available outside vendor folder.

I could fix it setting my default connection to the one I need, this implies changing the models that rely on the default as it is set now. Any options for a possible fix on this.

thx

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

This issue is also not locked and everyone is still free to discuss solutions to your problem!

Thanks!
