### ISSUE TITLE
prunerevokedaccessTokens does not delete revoked personal access tokens

### ISSUE THREAD

**Issue by haseebeqx** [laravel/passport#103]
i tried to delete revoked access tokens using ``Passport::pruneRevokedTokens();`` but it does not remove any revoked personal access tokens revoked using ``$token->revoke()`` as described in https://laracasts.com/discuss/channels/laravel/passport-how-can-i-manually-revoke-access-token
 but in database it sets revoked column value to 1

**Comment by craigpaul** [comment]
The `revoke()` method on the `Laravel\Passport\Token` model does indeed not delete anything. It force fills revoked to true.

```
/**
 * Revoke the token instance.
 *
 * @return void
 */
public function revoke()
{
    $this->forceFill(['revoked' => true])->save();
}
```

That is not affected at all by `Passport::pruneRevokedTokens()`. When you use that method, it is used when calling `revokeOtherAccessTokens()` on `Laravel\Passport\TokenRepository`. That method will do one of two things depending on how you have `$pruneRevokedTokens` set. If it is true, it will run a delete query, otherwise, it will update all matching tokens to have `revoked` set to true on the table. See below for the logic.

```
/**
 * Revoke all of the access tokens for a given user and client.
 *
 * @param  mixed  $clientId
 * @param  mixed  $userId
 * @param  bool  $prune
 * @return void
 */
public function revokeOtherAccessTokens($clientId, $userId, $except = null, $prune = false)
{
    $query = Token::where('user_id', $userId)
                  ->where('client_id', $clientId);

    if ($except) {
        $query->where('id', '<>', $except);
    }

    if ($prune) {
        $query->delete();
    } else {
        $query->update(['revoked' => true]);
    }
}
```

If you need to delete the token, you will have to do this instead. (Continuing on example from Laracasts link above)

```
$value = $request->bearerToken();
$id= (new \Lcobucci\JWT\Parser())->parse($value)->getHeader('jti');
$token= $request->user()->tokens->find($token);
$token->delete();
```

**Comment by haseebeqx** [comment]
thanks it worked

**Comment by yashagw** [comment]
this does not delete the refresh token from the database

**Comment by jarvar** [comment]
`$value = request()->bearerToken();
        $token= (new \Lcobucci\JWT\Parser())->parse($value)->getHeader('jti');
        $token= request()->user()->tokens->find($token);
        `$token->delete();`

This works fine for me
