### ISSUE TITLE
Passport issueToken throttles requests based on IP not username

### ISSUE THREAD

**Issue by gitstashgithub** [laravel/passport#1048]
- Passport Version: v7.3.0
- Laravel Version: v5.7.28
- PHP Version: 7.2
- Database Driver & Version:
MySql 5.7
### Description:
If I add throttle middleware to issueToken, it throttles requests only based on the IP not the username. 
```
Route::post('/oauth/token', [
        'uses' => '\Laravel\Passport\Http\Controllers\AccessTokenController@issueToken',
        'middleware' => 'throttle:10,1',
    ]);
```
When users in the same LAN shares same public IP, if one user attempts too many times, it will throttle all users.

**Comment by matt-allan** [comment]
The throttle middleware is [part of Laravel](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Routing/Middleware/ThrottleRequests.php), not Passport. Since this is a feature request it should probably be posted to [laravel/ideas](https://github.com/laravel/ideas/) instead.

That being said, only 1 of the 6 supported grant types includes a username so if Passport tried to throttle by username it would only work for password grants. For most grant types the user is redirected to the normal login page to enter their password so you would want to throttle that route instead.

**Comment by gitstashgithub** [comment]
Thanks @matt-allan, my project is an API so it doesn't have login page route. I guess I have to remove the throttle middleware.

**Comment by musamamasood** [comment]
I am facing the same situation, @gitstashgithub please let me know if you found any solution for this.

**Comment by gitstashgithub** [comment]
@musamamasood no, I just removed the middleware.
