### ISSUE TITLE
Passport::tokensExpireIn() used in PassportServiceProvider::registerAuthorizationServer() rather than Passport::refreshTokensExpireIn()

### ISSUE THREAD

**Issue by tentus** [laravel/passport#1058]
- Passport Version: 1 though 7 (up to 7.3.4 at the time of this writing)

### Description:
I haven't observed this actually causing any bugs, but it seemed off, so I thought I should mention it. 

On https://github.com/laravel/passport/blob/7.0/src/PassportServiceProvider.php#L107 the `AuthorizationServer` is passed `Passport::tokensExpireIn()` for the TTL of the 1RefreshTokenGrant1, while the actual grant is passed `Passport::refreshTokensExpireIn()`. Same goes for `AuthCodeGrant` and `PasswordGrant`, fwiw.

Again, I haven't actually noticed this causing any problems, which is why I omitted most of the issue template, but it still looks like an oversight.

**Comment by driesvints** [comment]
Hey @tentus. If you look a little bit below you'll see that the `refreshTokensExpireIn` is correctly passed when making the grants. Why this was done in this fashion I don't know because the code was built before I joined Laravel. If there's no bug atm let's just leave it as is for now. Thanks for mentioning this.
