### ISSUE TITLE
Support hashing tokens

### ISSUE THREAD

**Issue by matt-allan** [laravel/passport#1067]
It would be great if Passport supported hashing tokens, similar to the way [you can hash tokens with the API guard](https://laravel.com/docs/5.8/api-authentication#hashing-tokens).

I looked through the existing issues and saw #641 but that issue is about hashing the client ID and secret.

Hashing the access and refresh tokens is a bigger win for security in my opinion because:
- The client secret needs to be stored in plaintext by the client anyway but the tokens do not.
- Stealing a client secret lets you impersonate the client, but won't normally give you access to user's data. Stealing an access or refresh token does give you access to user's data.

It would be great if we could ship this feature for 8.0. I would be willing to write the PR.

**Comment by driesvints** [comment]
Wouldn't this technically break existing Passport apps if this was implemented?

**Comment by matt-allan** [comment]
I was thinking it would be opt in like it is with the api guard.

**Comment by driesvints** [comment]
@matt-allan that definitely makes sense. Feel free to attempt a PR :)

**Comment by corbosman** [comment]
@matt-allan what exactly do you want to hash?  Hashing any content from the token is not really useful,  because then you'd have to be able to provide the hashed content to laravel, which defeats the purpose. And in the passport token database there isn't much to hash.  The difference between the api guard and passport is that with passport, tokens aren't stored server-side. Only their id is.

**Comment by matt-allan** [comment]
Yeah sorry, I misunderstood what was happening. I was thinking of the League OAuth Server v4 where the token 'ID' was the actual access token used by the client. Since Passport is providing a signed JWT that isn't stored on the server we shouldn't need to hash the token IDs.
