### ISSUE TITLE
Support issuing tokens without a request or response

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/passport#1123]
I simply want to issue access tokens in a controller method. The request includes everything that's needed to authenticate and issue a token with the password grant client (email and password), but it doesn't include `client_id`, `client_secret` and `grant_type`.

If I want to call `AccessTokenController::issueToken` or `AuthorizationServer::respondToAccessTokenRequest` directly, I have to provide a request with these parameters. This leads to the following workaround:

``` php
$client = DB::table('oauth_clients')->where('password_client', 1)->first();
$request->request->add([
    'username'      => $request->input('email'),
    'client_id'     => $client->id,
    'client_secret' => $client->secret,
    'grant_type'    => 'password',
]);

$requestFactory = new DiactorosFactory();
$serverRequestInterface = $requestFactory->createRequest($request);

$response = $accessTokenController->issueToken($serverRequestInterface);

$token = json_decode($response->getContent());
```

I would like to be able to issue tokens with just one method call, instead of all of this. This would require a method similar to `respondToAccessTokenRequest`, that expects an array as input and returns an array (or object).

**Comment by driesvints** [comment]
*Why* do you want this?

**Comment by WouterFlorijn** [comment]
@driesvints In our application, users are able to file a complaint while in the same form registering an account. Therefore, it would be great if I could create the complaint and user, and return the tokens in the same request/response.

**Comment by driesvints** [comment]
@WouterFlorijn that would be under the idea that the client already exists right?

**Comment by driesvints** [comment]
I think there could be a potential implementation for this. @WouterFlorijn if you could describe a little more into detail how exactly you'd use this code-wise that'd be great. Feel free to send in a PR.

**Comment by WouterFlorijn** [comment]
@driesvints I guess it could look something like this:

```php
$client = DB::table('oauth_clients')->where('password_client', 1)->first();
$input = [
  'email' => $email,
  'password' => $password,
  'grant_type' => 'password',
];
$server = app(AuthorizationServer::class);
$token = $server->getAccessToken($client, $input); // ['access_token' => '...', ...]
```

Alternatively, passing the `client_id` and `client_secret` through the array instead of the first parameter would also be fine. And semantically, something called `AuthorizationServer`, might not be the best class for this if the `getAccessToken` method doesn't use any requests/responses.

Unfortunately, it looks to me like all the related classes (e.g. `AuthorizationServer` and grant classes) are coupled with requests and responses. This makes validation very easy, but does mean it would require quite some refactoring to implement this cleanly I think, unless you would have an idea I didn't consider.

I would like to look into this, but realistically I'm very busy with other things, so I wouldn't count on me 🙃

**Comment by matt-allan** [comment]
The underlying grant in league/oauth2-server [requires the request](https://github.com/thephpleague/oauth2-server/blob/4c05600c6a606036d1d67af97ba26397827c1531/src/Grant/PasswordGrant.php#L46) so if Passport offered this it would need to create a request and parse the response like you are doing now, similar to [how the personal access token factory works](https://github.com/laravel/passport/blob/c264db61f4305d9c87e6bdf1a4a13583316b65d8/src/PersonalAccessTokenFactory.php#L70).

That being said I don't think Passport should encourage this pattern. [The password grant is strongly discouraged for browser based apps](https://tools.ietf.org/html/draft-parecki-oauth-browser-based-apps-02). Proxying requests like this allows anyone to hit the endpoint and obtain access and refresh tokens without knowing the client secret. The authorization server thinks it's interacting with a confidential client but it's essentially a public client. This makes it impossible to know if the client should receive a refresh token ([Browser based apps aren't supposed to get refresh tokens](https://tools.ietf.org/html/draft-parecki-oauth-browser-based-apps-02)), if the token lifetime should be reduced, etc. based on the client type.

Granting the token in a separate request has a small amount of overhead but the upside is it's a standards compliant request and response format supported by existing OAuth 2.0 clients.

**Comment by driesvints** [comment]
@themsaid mentioned to me that he also needed this a couple of times. @sephster do you have any thoughts on this?

**Comment by driesvints** [comment]
@matt-allan the note about the standards compliancy is a good one though. Let's review this a bit more before we create a pr.

**Comment by Sephster** [comment]
It would be good to find out more about the use case but this doesn't seem to fit with what OAuth was intended for so I would question the applicability of use Passport in this manner and suggest this isn't progressed.

In general OAuth is used to provide a client access to protected resource. The client will either act for itself or on behalf of a user.

In this scenario described, it seems the end user doesn't have a pre-existing relationship with the protected resource so a couple of questions come to mind in the context of OAuth:

* How can the end user grant access to something that doesn't exist?
* Why is the client trying to gain access to a protected resource that doesn't exist.

If this was implemented I would expect there would be some serious security issues introduced as @matt-allan has intimated.

Ultimately it doesn't fit with the OAuth use case which is why this isn't supported currently. It would be good to find out what this token is used for. What the client is (e.g. is the client and the protected resource the same application), and why the user doesn't have an account, but my gut feeling is that OAuth is not appropriate for this use case.

**Comment by WouterFlorijn** [comment]
@Sephster I understand your points, just to clarify:

The resource in my case would be the user's account, which is created in the same request. Therefore it doesn't exist when the request is sent, but it is created during the request.

A slightly different suggestion could be to decouple Passport from requests as much as possible and accept arrays or individual arguments to pass data instead. The methods and data passed could be kept the same, and no new methods would need to be added. Any request/response-related logic could be handled in for example the controller classes. This would make it easier to extend Passport and possibly open up more use in different frameworks. Do you have any thoughts on that?

**Comment by Sephster** [comment]
Thanks for the quick response @WouterFlorijn. The creation of users is not something that is handled by OAuth. It is always expected that the user or client will already have a presence on the protected resource and I think this is where your issues are coming in.

If we were to apply this to the OAuth flow as it is expected, it should work something more like this. I'm assuming there is a web app (App A) and a protected resource here (App B):

# Actions Performed in App B Only

* User raises a complaint
* User is asked if they want to create an account
* User creates an account

# Actions Performed in App A _after_ complaint is raised

* User wants to access complaint info from App B
* User clicks link to initiate auth code flow. Is redirected to App B login
* User gives credentials they have previously created in App B
* Auth code is created and passed back etc. Eventually App A gets an access code they can use

In order to comply with OAuth, the account creation _must_ happen in the application that is housing the protected resource. I would just shift where this functionality is if possible to solve your issue, perhaps with a simple redirect to a form hosted on the protected resource app.

Unfortunately it isn't possible to decouple Passport from http requests because the underlying OAuth server requires some form of an http request to be issued. This is because this is compliant with the OAuth spec.

I would recommend that Passport is not changed for this use-case. It seems that the easiest and most secure option would be to change your user creation workflow or build something custom to create your user over an API endpoint if this isn't possible that doesn't rely on any OAuth 2 grants.

**Comment by driesvints** [comment]
We're going to follow @Sephster here on this one, sorry. 

@Sephster Thanks for the thorough review of this one.
