### ISSUE TITLE
AccessTokenTrait changed function convertToJWT from public to private

### ISSUE THREAD

**Issue by marija-bogdanovic** [laravel/passport#1129]
Hi,
why did you change this, was this necessary? 
There is a good way for adding claims into passport access token by overriding function convertToJWT and now I cannot do it anymore. I upgraded Laravel to 6.* but still, need to use "laravel/passport": "7.*", in order to make it work in the same way.
 Would it be some security issue if you revert it? 
Thanks in advance.

**Comment by Sephster** [comment]
This was changed in the OAuth2-Server, not Passport. The change was made two years ago. From memory, it was because we added a `_toString()` method to generalise the access token interface so that in future, you could perhaps use paseto if they wished. We wanted to remove references to specific outputs if possible.

We do need to add a native way to add custom claims and there is an issue open for this. We would welcome any PRs for this. Thanks

**Comment by marija-bogdanovic** [comment]
Oh, ok then,  thank you Sephster for your answer.
