### ISSUE TITLE
Generating client by command return Aborted.

### ISSUE THREAD

**Issue by LordOfDav11** [laravel/passport#1178]
- Passport Version: 8.3.1
- Laravel Version: 6.13.1
- PHP Version: 7.4.0
- Database Driver & Version:  10.4.10 MariaDB

### Description:
I want create client with PKCE feature, so I have create client by _php artisan passport:client --public_, but I'm getting:
E:\project> php artisan passport:client --public
 Which user ID should the client be assigned to?:
 >
  Aborted.
E:\project>

I'm getting this always after i hit a enter for confirm command. There is no chance to write a user ID and also I tried a different CLI. Is there any other way to create a client with PKCE feature?
Thanks for help.

### Steps To Reproduce:

laravel new
composer require laravel/passport
(edit .env for DB connection)
php artisan migrate
php artisan passport:install (running without problem, generate 2 clients)

php artisan passport:client
OR
php artisan passport:client --password
php artisan passport:client --public
php artisan passport:client --client

none of them working, always return Aborted

**Comment by LordOfDav11** [comment]
So I downgrated php to 7.3.12 version and commands works. Also I noticed that I always received invalid_client error status when grant_type=authorization_code and authorization informations was correct. This problem was also solved and OAuth now works fine. I hope this helps to find potential bug.

**Comment by driesvints** [comment]
I can run the above command just fine with the above versions.

**Comment by julesgraus** [comment]
I got the same kind of issues in an existing laravel app. I did install laravel passport on an
Laravel Framework 6.17.0 installatation using `composer require laravel/passport`. Because i want to use the Authorization Code Grant with PKCE feature, i did run `php artisan passport:client --public` after the initial setup steps like stated in the 6.x manual of laravel. And emediately after i run the command i do get 'Aborted' too. Maybe it does not happen in new installations. But it happened in mine. The laravel project i use started at laravel 5.8 and i did upgrade it to 6 a while ago, and now to 6.17.
