### ISSUE TITLE
Key file permissions are not correct on windows: Key file "file://F:\\......\\oauth-private.key" permissions are not correct, recommend changing to 600 or 660 instead of 666

### ISSUE THREAD

**Issue by parsakafi** [laravel/passport#1180]
Hello
I have a problem with Laravel Passport version ^7.3 on Windows 10

```
Key file "file://F:\\......\\oauth-private.key" permissions are not correct, recommend changing to 600 or 660 instead of 666
vendor\league\oauth2-server\src\CryptKey.php
```

```
"laravel/framework": "5.8.*",
"laravel/passport": "^7.3",
"laravel/tinker": "^1.0",
```

I checked value of $keyPathPerms variable on CryptKey.php line 53
This variable set to 666

I changed this line and worked for me
`if (in_array($keyPathPerms, ['400', '440', '600', '640', '660','666'], true) === false) `

**Comment by Sephster** [comment]
This is a user notice rather than an error. I think your script will continue to run regardless. It is intended for Linux based systems and doesn't apply to Windows. For this reason, we have a parameter on the CryptKey class which allows you to disable this check if you want. I don't think this feature has been implemented into Passport though.

**Comment by driesvints** [comment]
Feel free to send in a PR if you think something should be added for this to Passport.

@Sephster thanks for pitching in
