### ISSUE TITLE
Call to undefined method Auth::extend

### ISSUE THREAD

**Issue by oinpentuls** [laravel/passport#1224]
- Passport Version: 8.4.0
- Laravel Version: 6.9.0
- PHP Version: 7.2.24
- Database Driver & Version: Postgresql 10

### Description:
Have laravel/passport fresh install, then got 
` Uncaught Error: Call to undefined method Illuminate\Support\Facades\Auth::extend()
in /var/www/html/my-web/vendor/laravel/passport/src/PassportServiceProvider.php:260`

this the piece of the code from 
` /var/www/html/my-web/vendor/laravel/passport/src/PassportServiceProvider.php`

```
/**
     * Register the token guard.
     *
     * @return void
     */
    protected function registerGuard()
    {
        Auth::resolved(function ($auth) {
            $auth->extend('passport', function ($app, $name, array $config) {
                return tap($this->makeGuard($config), function ($guard) {
                    $this->app->refresh('request', $guard, 'setRequest');
                });
            });
        });
    }
```

### Steps To Reproduce:
change `$auth->extend` in the closure to `Auth::extend`

but i assume there is a far more better way than this

**Comment by driesvints** [comment]
I can't reproduce this. Passport works just fine for me.

**Comment by oinpentuls** [comment]
it's kinda strange. i'll try on different project, thanks.

**Comment by flosej** [comment]
@oinpentuls If it can helps I had the same issue, I had a singleton aliased 'auth' which caused the error, I've resolved the issue by changing the alias name.

**Comment by makao91** [comment]
Have the same issue after upgrade laravel framework from 5.4 to 8.40.
In my case, i have just forgotten to change index methods in controllers and routes in routes/api.php as you can read in laravel upgrade guide.
https://laravel.com/docs/6.x/upgrade
"Authorization policies attached to controllers using the authorizeResource method should now define a viewAny method, which will be called when a user accesses the controller's index method. Otherwise, calls to the index method of the controller will be rejected as unauthorized."
