### ISSUE TITLE
The access token expires at the same time as the refresh token

### ISSUE THREAD

**Issue by ursuleacv** [laravel/passport#125]
I have added 

```
$now = new \DateTime('now', new \DateTimeZone('UTC')); //today is: 2016-10-09 18:07:45

Passport::tokensExpireIn($now->add(new \DateInterval('P1D'))); //1 day

Passport::refreshTokensExpireIn($now->add(new \DateInterval('P30D'))); //30 days
```

in AuthServiceProvider in boot method. And I noticed in database the expires_at values are exactly the same for access token and refresh token: 2016-11-09 18:07:45

Is this normal?

When I try to request another access token using the refresh token I get:

`The refresh token is invalid`

**Comment by craigpaul** [comment]
Hey @ursuleacv,

The problem you're having (I'm fairly sure) is because you're using the same `DateTime` instance. You can either use two different instances like the following.

```
$now = new \DateTime('now', new \DateTimeZone('UTC'));

Passport::tokensExpireIn($now->add(new \DateInterval('P1D'));

$now = new \DateTime('now', new \DateTimeZone('UTC'));

Passport::refreshTokensExpireIn($now->add(new \DateInterval('P30D'));
```

That will solve your problem, but there is a cleaner way. That way is using `Carbon` instead of raw `DateTime` classes.

```
Passport::tokensExpireIn(Carbon::now()->addDays(1));

Passport::refreshTokensExpireIn(Carbon::now()->addDays(30));
```

Hope this helps you out.

**Comment by ursuleacv** [comment]
Thank you.  It's working now.
