### ISSUE TITLE
Show all authorized third party apps

### ISSUE THREAD

**Issue by hcphoon01** [laravel/passport#1363]
I'm currently getting in to using passport for authorization for a third party public API, and I was wondering if it would be possible to have a feature, as part of the JSON API, that allows a request to an endpoint that returns all authorized third party apps the authenticated user has authorized, in order to both view and then deauthorize them

**Comment by driesvints** [comment]
How would you practically tackle this?

**Comment by hcphoon01** [comment]
Possibly have another table in the database like `oauth_authorized_clients` that contains a user id column and client id column, then have an endpoint for example `/oauth/authorized`. A GET request to that endpoint gives a list of authorized clients for the authenticated user, and a DELETE request to that endpoint deauthorizes the client

**Comment by driesvints** [comment]
I'm wondering if this isn't better handled in userland. I can definitely understand the use case though. But since OAuth2 Server doesn't provides this out of the box for us to wrap around I think this isn't something we're gonna work on ourselves. If you're willing to work on a PR however we might consider it.
