### ISSUE TITLE
AccessToken generated via PasswordGrant cannot be decoded using TokenGuard::decodeJwtTokenCookie - "Algorithm not allowed"

### ISSUE THREAD

**Issue by kurbar** [laravel/passport#1398]
- Passport Version: 10.1.0
- Laravel Version: 8.20.1
- PHP Version: 8.0.1
- Database Driver & Version: MySQL 5.7

### Description:
I'm generating access tokens using PasswordGrant and then returning them as cookies. I have the cookie name synced with `Passport::cookie()` to trigger the `TokenGuard::decodeJwtTokenCookie` handler to authorize the user.

However `decodeJwtTokenCookie` has hard-coded `HS256` algorithm whereas PasswordGrant tokens are generated with the `RS256` algorithm.

This causes the guards decode step to fail with an `Algorithm not allowed` exception.

### Steps To Reproduce:
1. Set the cookie name in the service provider - `Passport::cookie('token')`
2. Issue an access token using PasswordGrant via `/oauth/token`.
3. Return the access token as a cookie named `token`.
4. Make a request against an `auth:api` enabled route ensuring the cookie is passed along with the request.

**Comment by driesvints** [comment]
Heya. This doesn't seems like a Passport issue to me since you have a pretty custom setup. I don't think we document this kind of usage.

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by kurbar** [comment]
@driesvints In that case would it be more viable for an extendability enhancement?

The main issue is that `TokenGuard::decodeJwtTokenCookie` has hard-coded allowed algorithms (https://github.com/laravel/passport/blob/10.x/src/Guards/TokenGuard.php#L268).

If this was configurable via Passports config, it would go a long way.

**Comment by driesvints** [comment]
You're always free to attempt a PR 👍

**Comment by riel-tbdev** [comment]
I have the same issue @kurbar the TokenGuard checks for the cookie but there's a mismatch of algorithm.
