### ISSUE TITLE
Changing the database connection 

### ISSUE THREAD

**Issue by omaralshamass91** [laravel/passport#1487]
- Passport Version: v10.0.1
- Laravel Version: 8.62.0
- PHP Version: 7.4.24

### Description:
when setting up `$connection` in the model, it does not get affected and still reads the DB connection from the .env file

### Steps To Reproduce:
just try to add a new connection in your model and check if it goes to use it or not.

I believe it is related to this line of code at https://github.com/laravel/passport/blob/10.x/src/Client.php#L194
it should be written opposite, is not it? 
```
$this->connection ?? config('passport.storage.database.connection');
```

**Comment by driesvints** [comment]
Heya, no the current one is correct. That config setting is meant as an overwrite-all. So you'd set it to set the DB connection for all models. This is because you'd usually want all of your Passport models in the same database. If you don't want that and want them in separate databases then you need to overwrite the config, make the default connection empty and set a connection on each model separately.

**Comment by driesvints** [comment]
Export the config with `vendor:publish` and adjust the config itself to remove the default `mysql`. 

On second thought I think I might be inclined to agree that the sequence of the operation is wrong as you suggested. We could maybe look into changing it for the next master release. You're always free to send in a PR for that if you want.

**Comment by liuxingyuxia** [comment]
I think I met something similar

I dynamically switch the database

Trying to get user information prompts me to get user information

Is it settled now



Please forgive me for using translation software to translate the text
