### ISSUE TITLE
AuthorizationController gets TokenGuard instead of StatefulGuard

### ISSUE THREAD

**Issue by pontoffeltier** [laravel/passport#1602]
- Passport Version: 11.3.0
- Laravel Version: 9.42.2
- PHP Version: 8.1.13
- Database Driver & Version: mysql 8.0.30

### Description:
I followed the documentation for Passport to implement "Authorization Code Grant with PKCE". When I am trying to send a GET request to /oauth/authorize, I get the following error message:
```
Laravel\\Passport\\Http\\Controllers\\AuthorizationController::__construct(): Argument #3 ($guard) must be of type Illuminate\\Contracts\\Auth\\StatefulGuard, Laravel\\Passport\\Guards\\TokenGuard given
```
What I found in the source code was, that with the [PR 1577](https://github.com/laravel/passport/pull/1577) the `Laravel\\Passport\\Http\\Controllers\\AuthorizationController` now has a third parameter with the type of `Illuminate\\Contracts\\Auth\\StatefulGuard`. The problem is, the only guard in this package (which is bound in the `Laravel\Passport\PassportServiceProvider`) is the TokenGuard - which does not implement the StatefulGuard interface. 

**I totally expect that I am missing something important here, but for now I think this is a bug.**

### Steps To Reproduce:

As stated in the documentation:
- Install laravel/passport
- In `config/app.php` set `guards.api.driver` to `passport`
``` 
   'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],
```
- Create a client: `php artisan passport:client --public` with ID set to `1` and default values for name and redirect
- Make a GET request (I used postman) to `/oauth/authorize` - I tested with and without the query parameters, both give the same error response

**Comment by driesvints** [comment]
@hafezdivandari can you weigh in here?

**Comment by hafezdivandari** [comment]
@pontoffeltier I guess your default guard (the `auth.defaults.guard` config value) is not `web` right? 
Would you please add `'guard' => 'web'` to `config/passport.php` configuration file and try again?

**Comment by hafezdivandari** [comment]
> I followed the documentation for Passport to implement "Authorization Code Grant with PKCE". When I am trying to send a GET request to /oauth/authorize, I get the following error message...

@pontoffeltier You shouldn't send a GET request to `/oauth/authorize` but you should make a **redirect** request to your application's `/oauth/authorize` route: https://laravel.com/docs/9.x/passport#code-grant-pkce-redirecting-for-authorization

**Comment by pontoffeltier** [comment]
> @pontoffeltier I guess your default guard (the `auth.defaults.guard` config value) is not `web` right? Would you please add `'guard' => 'web'` to `config/passport.php` configuration file and try again?

Thanks, that was it. So sorry for the confusion, my `config/passport.php` did not contain any `guard` value so I simply overlooked it

**Comment by hafezdivandari** [comment]
@pontoffeltier I sent a PR for that: #1603

**Comment by jlambe** [comment]
@driesvints @hafezdivandari We installed the package on a project and we're facing the same issue. There is a mistake either in source code or either in the official documentation of Laravel Passport which leads to some confusion here.

For example, the official documentation says the following:

Finally, in your application's `config/auth.php` configuration file, you should define an `api` authentication guard and set the driver option to `passport`. This will instruct your application to use Passport's `TokenGuard` when authenticating incoming API requests:

```php
'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
 
    'api' => [
        'driver' => 'passport',
        'provider' => 'users',
    ],
],
```

But as mentionned in the original comment, the `AuthorizationController` as a type of `StatefulGuard` while the `TokenGuard` class is only implementing the `Guard` class.

The solution mentioned from @hafezdivandari is to use the default `web` guard... which works because it returns a `StatefulGuard` instance...

So the question is why bother having a `TokenGuard` under the `passport` guard key and explicitly tell the users to do so if the solution is to keep the default `web` guard. If the `TokenGuard` class is supposed to be used, then it is broken because it does not implement the right interface or it's the `AuthorizationController` that should require a `Guard` instance as a dependency instead of the `StatefulGuard` one.

Currently the `TokenGuard` class seems to be pointless in the package. Of course it works to use the `web` guard but something is misleading the users here.

Do you think you can share more feedback on this issue please ?

Thanks

**Comment by hafezdivandari** [comment]
@jlambe Your app uses Passport driver for its `api` guard (uses `TokenGuard`) and the Passport uses `web` guard to authorize the user (needs a `StatefulGuard`). So by default:
* `config/passport.php` config file contains `'guard' => 'web'` 

    https://github.com/laravel/passport/blob/b33fa25458c26465e6acf5ed6989ba48e2628eef/config/passport.php#L5-L16
* `config/auth.php` config file contains 

    ```php
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],
    ```

You shouldn't face any issue with a fresh install and following the instruction of the official docs.

**Comment by jlambe** [comment]
@hafezdivandari In our implementation, I had to provide a custom guard called `oauth`  because the `api` one is already using a `token` driver for a third-party package.

So the docs got me confused a bit here, but thanks to your message, it strikes to me that the passport configuration guard is for "users" requests only. So when a client is trying to access a resource from our server with an access token, we must declare the endpoints to use the auth middleware with our custom guard that uses the `passport` driver, am I correct ?

This means that resources that require an access token must be declared like so for example:
```php
// Based on our custom guard...
Route::get('endpoint', function () {
    // return json
})->middleware('auth:oauth');
```

Let me know if I'm not correct! Thanks for your feedback.
