### ISSUE TITLE
Token scopes no longer stored the same.

### ISSUE THREAD

**Issue by joelharkes** [laravel/passport#1697]
### Passport Version

11.9.2

### Laravel Version

latest

### PHP Version

8.2

### Database Driver & Version

SQL Server

### Description

we recently upgraded: https://github.com/laravel/passport/compare/v11.8.8...v11.9.2

We have some overwrites on the passport library but found a problem in the code:

Before we used to store the scope as: "scope1 scope2" space delimited string.
But now the code expects a Json_encoded field, otherwise it will always return `true` as the result for scope checking:

<img width="594" alt="image" src="https://github.com/laravel/passport/assets/2960938/1c9dc398-8467-4c75-bbd8-443db5d1785b">

<img width="442" alt="image" src="https://github.com/laravel/passport/assets/2960938/4bba5e12-e783-4ebe-9647-dad5f783a710">

### Steps To Reproduce

Use old passport version 11.8.8 store a client scopes as space delimited string. but not it stores it as json_encoded array.

we had to do quite a migration to not break our codebase.

**Comment by driesvints** [comment]
@axlon thoughts here? So far only one report though. The PR is already three months old almost so not sure if reverting is an option?

**Comment by driesvints** [comment]
@joelharkes how are you storing scopes as a space delimiting string? Can you share some code?

**Comment by axlon** [comment]
@driesvints In my PR I assumed the changes would always be fully backwards compatible, because any previously existing scopes column would already have a cast in place to have the scopes come out of the model as an array, overwriting the casts provided by Passport's client.

It appears that @joelharkes is manually casting the scopes (encoding them before passing them to the model, and decoding them outside of the model). The easiest way to fix this would probably be to either make eloquent not use a cast for the scopes (by extending the client model and removing that specific cast) or creating a custom cast that deals with space delimited strings (which would require some code changes to classes that access the scopes on the client).

**Comment by driesvints** [comment]
@axlon thanks! I'll await a code example from @joelharkes before continuing.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
