### ISSUE TITLE
Get user from request always returns null (only Auth::guard('api') works)

### ISSUE THREAD

**Issue by DanielOlarte** [laravel/passport#237]
Hello everyone

I have been moving my API to Laravel 5.3 and Passport, I'm creating the whole authentication and authorization flow, and when I add the middleware of the API in my route, like this:

```
Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:api');

```
On the auth.php file, I have this:

```
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
```

Also, the middleware for auth is:
`
 'auth' => \Illuminate\Auth\Middleware\Authenticate::class,`

In the RouteServiceProvider, I have this:

```
Route::group([
            'namespace' => $this->namespace,
            'middleware' => 'api',
            'prefix' => 'v1',
        ], function ($router) {
            require base_path('routes/api.v1.php');
        });
```

And the API middleware group is:

```
    protected $middlewareGroups = [
        'api' => [
            'throttle:100,1',
            'bindings'
        ],
    ];

```
In my AuthServiceProvider, I followed some suggestions to add this:

```
        Passport::tokensExpireIn(Carbon::now()->addDays(15));

        Passport::refreshTokensExpireIn(Carbon::now()->addDays(30));
```

But, the weird thing is that I managed to pass the middleware, but the method $request->user() is always null, I tried with Password Grant and Personal Access Clients.

Then, I'm trying to use Scopes, but I can't pass them because of this issue, then, my only idea for the moment is creating a custom middleware that uses Auth::guard('api')->user() which works without issues.

Did I miss something on this?

Thanks

**Comment by morloderex** [comment]
Are you sure you are sending the access token correctly to the provided endpoint? 

it has to be "Bearer {some token}" on the authorization header for the given endpoint you are trying to access?

**Comment by DanielOlarte** [comment]
Yes, I'm sending the token on the Authorization header as Bearer access_token and also the Accept application/json header, but even if I sent that incorrectly, why Auth::guard manages to get the user?

**Comment by joshbodine21** [comment]
My code is exactly like the above and I am passing the bearer token the same way and I am having the same issue on 5.3. I am going crazy!

**Comment by joshbodine21** [comment]
It seems to me that the problem (at least in my case) is my desire to use "username" instead of "email" as my login column.

When requesting a token using the password grant, I added the following function to my User model:

`
public function findForPassport($username) {
      return $this->where('username', $username)->first();
}
`

This works great and I am able to get an authentication token successfully. However, when I then call any of my pages that require authentication witht the "auth:api" middleware, and I pass the bearer token in the header, I always get unauthenticated because my user is null. When I dig down into the following page

vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php

and look at the "check" function where it is ultimately failing and returning an authentication exception, the following is null:

`$this->user()`

It appears that in the page references below, the following function is my problem; I just don't know how to properly override the "username()" function. If I change "email" to "username" here, things then work fine, but I don't want to edit the vendor file. I don't have a LoginController because I am using passport to grab a token and then pass it. How do I override this?

vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php

`public function username()
{
        return 'email';
}
`

**Comment by DanielOlarte** [comment]
I managed to resolve the issue, before my migration to Passport, I was using this package:

https://github.com/cartalyst/sentinel/

And I loaded their provider, but if you can see here: https://github.com/cartalyst/sentinel/blob/2.0/src/Laravel/SentinelServiceProvider.php, they define the userResolver too, then, that one was having the priority over the Passport one.

I don't need the package anymore, I removed and removed the service provider that they have, and everything is working perfectly.

**Comment by mohamedsharaf** [comment]
php on apache
cgi , fcgi remove authorization headers for security 
if u test same code on localhost will work 
try to run php on different handler suphp

**Comment by zarehesmaiel** [comment]
if you are using username instead of email for credential; insert this method at your User model:

function findForPassport($username) {
     return $this->where('username', $username)->first();
}

**Comment by rener172846** [comment]
@mohamedsharaf  My cloud server is also using CGI/FastCGI and the Authorization header always missing.
What's the solution for that?

**Comment by leonelngande** [comment]
> Are you sure you are sending the access token correctly to the provided endpoint?
> 
> it has to be "Bearer {some token}" on the authorization header for the given endpoint you are trying to access?

@morloderex your question made me go back to my jwt interceptor and I realized my issue was a spelling error. I used `Authorisation: Bearer ${token}` instead of `Authorization: Bearer ${token}`. Been trying to fix this since yesterday, thanks.
