### ISSUE TITLE
[Security Concern/Flaw/Bug] An API Authorization token with changed last character is still allowed authorization.

### ISSUE THREAD

**Issue by jeremykenedy** [laravel/passport#257]
Testing from Postman....

Certain invalid tokens allow access when they probably shouldn't. 
When the last char of the token is incremented to its next (ASCII) value the endpoint is still allowed access but used to return a 401 as expected.

For example, incrementing the last char 'Q' to 'R'  (or next 3 letters proceeding capitalized) in a given token and then accessing an endpoint, the request succeeds when it shouldn't.

The seems like a very big security issue.

**Comment by jeremykenedy** [comment]
I would really like this looked into as it can be serious and makes me question what else is wrong.... Let me know if it would help if I setup a public instance so that you can see for yourself.

**Comment by craigpaul** [comment]
@jeremykenedy Passport doesn't actually handle generating the tokens. That is handled by `thephpleague/oauth2-server` so if there is an issue it would be in that package. Also...just saying but if someone can manage an over 1000 character access token, the last character being able to be changed + / - 3 values isn't really the biggest concern you would have in that moment. That's just my thoughts though, perhaps others can weigh in on this.

**Comment by JuanDMeGon** [comment]
Maybe I'm missing something but although it is not an expected behavior, every token and its +3 variants still having the same expiration time and refresh_token. It is something like create four access_tokens immediately for the same user and client and using the same refresh token.

Again, maybe I'm missing something, and I know it is not an expected behavior, but it does not seem like a security concern to me.

Do you have any case on which this can be used by someone to make "dirty" stuff?

**Comment by jeremykenedy** [comment]
Thank you very much for checking it out 👍.  I am totally understanding of it only being the last character with a +3 variant, however, it still concerns me that there is any variant on a very specific token.  

Btw, I totally love Laravel and all the products. I Send big thanks to all the people that put in all the hard awesome work!

The initial message above is one I am facing from QA after failing an automated test.

**Comment by jeremykenedy** [comment]
I have also reached out to https://github.com/thephpleague/oauth2-server/issues/702 as well. Thank you again!

**Comment by alexbilbie** [comment]
I'm copying my comment from thephpleague/oauth2-server#702 here for future reference:

---

First of all this is really irresponsible disclosure. Both this repository and the Laravel repositories have got guidance on how to report security vulnerabilities.

Second this isn't an issue due to the way base64 character encoding works. Depending on the encoded data you may be able to change a few characters at the end of the token without affecting modifying the encoded data.

So this isn't a security issue.

**Comment by jeremykenedy** [comment]
@alexbilbie wow, you call 8 lines of a readme.md a guidlines. 

I find it hard to believe that I can change a +3 variant on an encrypted token and that is not a security issue.

Clearly, security isn't your top concern.

**Comment by taylorotwell** [comment]
Closing and locking per Alex's request.
