### ISSUE TITLE
How to work with OAuth errors

### ISSUE THREAD

**Issue by lotarbo** [laravel/passport#289]
Hi, what is the right way to custom or work with errors? I mean when we have invalidClient error, this auth popup is bad for me, mb better redirect to client site with some message?
And how change error? I read  http://www.kingpabel.com/oauth2-exception-custom-error-message/
but it works only for clean League\OAuth2, passport has own HandlesOAuthErrors, can somebody help?

**Comment by sebastiaanluca** [comment]
Running into the same issue. Thought my exception handler was botched, but turns out Passport intercepts all errors and returns a plain text string. That's not really useful, to just output raw exceptions to the user without a chance to format these as a developer?

@themsaid @taylorotwell What's the course here to disable/extend this custom Passport exception handler?

Similar issue: https://github.com/laravel/passport/issues/97

**Comment by deividaspetraitis** [comment]
Not sure what's wrong to catch and handle these in Hander.php:

`    /**
     * Determine if the given exception is an OAuth2 exception.
     *
     * @param Exception $e
     *
     * @return bool
     */
    public function isOAuthException(Exception $e)
    {
        return $e instanceof \League\OAuth2\Server\Exception\OAuthServerException
                ||
                $e instanceof AuthenticationException;
    }`

In case you want to determine specific exception you can use `$e->getErrorType()`.

**Comment by EdwardNelson** [comment]
The exceptions do not bubble up to the exception handler. Passport catches them

**Comment by deividaspetraitis** [comment]
Yea, seems you guys are right. 

If I'm correct error handling happens using predefined controllers that calls  `$this->withErrorHandling()` function that refers to `HandlesOAuthErrors` trait.

Such handling is not useful not only in case when you do need to catch exception but there is some headache  when you do need to return these errors in some other format for example JSON, XML, etc.

What I have done so far in order to solve this I just created my own controllers and removed such handling. 
That means that you must to:

-  Emit `Passport::routes();` from your `AuthServiceProvider ` class `boot` method,  
-  Copy original contoller that will issue tokens ( in this example let's consider it will be `AccessTokenController` ) and remove `withErrorHandling()`
- Define manually routes for your created controller

For example: Please see original `AccessTokenController`: https://github.com/laravel/passport/blob/2.0/src/Http/Controllers/AccessTokenController.php and my re-defined: https://gist.github.com/deividaspetraitis/7c3958381d33a06b511d17e2e22b8bb5

**Comment by erkanarslan** [comment]
@EdwardNelson Notice that passport catches the Exceptions than calls your applications app/Exceptions/Handler. You can do whatever you want here.

**Comment by sebastiaanluca** [comment]
@themsaid @taylorotwell Is there a way to handle this in the app exception handler? Few months later and we still have issues with this. API just returns 500 for any wrong user input (e.g. wrong access token) and the apps that rely on it have no proper way of dealing with it since the returned data is not our proprietary JSON format.

**Comment by servocoder** [comment]
+1
It's extreamly problematic to implement custom exception handler for Passport so long as errors are caught in the HandlesOAuthErrors trait

**Comment by adiachenko** [comment]
I don't think this will work for everyone, but if you're developing an API for first-party clients, you can kinda sweep all that complexity under the rug by utilizing internal requests. Meaning, your client talks to a proxy instead of directly communicating with `oauth/token`. That way, you can simply **throw your own Exception whenever the latter returns anything but a 200**, include other resources onto response, inject client credentials automatically etc. 

Not the most elegant solution, but it's what I've been doing with Passport ever since it was released.

**Comment by Shadow2004** [comment]
These solutions all deal with exception coming from issue token routes but I am currently trying to deal with the errors coming from the middleware checks when authenticating a token. Currently I get one error back for everything, "Unauthenticated.". This comes from the Authenticate class but this seems daft as a token could be denied for multiple different reason. Any one got any ideas on how i can get around this?

**Comment by fjzboy** [comment]
maybe, the oauth/token route should not be accessed directly by client, you can define a custom route (ie.'/api/login'), in that route function, you can call oauth/token api, and process result before return a response to your client

**Comment by webdevog** [comment]
Hello I've also used some workaround solution using solution above.
It is not the best way of resolving the issue but maybe for somebody it could be useful:
class AccessTokenController extends PassportAccessTokenController
{
    /**
     * Authorize a client to access the user's account.
     *
     * @param  ServerRequestInterface $request
     *
     * @return \Psr\Http\Message\ResponseInterface
     * @throws \League\OAuth2\Server\Exception\OAuthServerException
     */
    public function issueToken(ServerRequestInterface $request)
    {
        try {
            return $this->convertResponse(
                $this->server->respondToAccessTokenRequest($request, new Psr7Response)
            );
        } catch (OAuthServerException $exception) {
            if ($exception->getCode() === 6) {
                $message = "E-mail and password doesn't match";
                $requestParameters = (array)$request->getParsedBody();
                $username = $requestParameters['username'] ?? null;
                if ($username && $user = User::where('email', $username)->first()) {
                    if ($user->status == UserStatuses::INACTIVE) {
                        $message = 'Please contact administrator to login the system';
                    }
                }
                abort(401, $message);
            }

            return $this->withErrorHandling(function () use($exception) {
                throw $exception;
            });
        }
    }
}`
`

**Comment by yushengbuilder** [comment]
@webdevog 我觉得这是一个人好的方式，因为token接口并不是专为点一前端设计的，可能多个前端之间的报错信息需求不是很相同。如果都后端重新定义会很繁琐。

**Comment by yushengbuilder** [comment]
@webdevog 我觉得这是一个很好的方式，因为token接口并不是专为单一前端设计的。可能多个前端之间的报错信息需求不是很相同。如果都后端重新定义会很繁琐。而且错误形式很多。

**Comment by rockoo** [comment]
This is still an issue 1+ years in...

**Comment by driesvints** [comment]
@rockoo you're free to send in a PR. Eventually I'll get to taking a look at this but I can't do everything at the same time. Would appreciate any help.

**Comment by EdwardNelson** [comment]
Are you planning on a PR?

**Comment by driesvints** [comment]
I've just sent in a PR which would make handling errors a lot easier. Please take a look at it and respond there if you like the new solution. I've added an example on how you can roll with your own implementation: https://github.com/laravel/passport/pull/937

After working on a solution I think the main reasoning why this is implemented so strictly is because you don't want to "leak" any sensitive information to your consumers of your library if stuff breaks.

Anyway, let me know what you think of the new solution on the PR and we'll merge it in a few days.

**Comment by pyragle** [comment]
HAVING THE SAME ISSUE RIGHT NOW IS THERE AN OFFICIAL ISSUE YET

**Comment by Cintrust** [comment]
HAVING THE SAME ISSUE ANY OFFICIAL FIX YET

**Comment by driesvints** [comment]
@Cintrust please see the above message

**Comment by driesvints** [comment]
The PR was merged and the refactor will be released with the next major Passport release.

**Comment by eithed** [comment]
Given that currently there's no way to re-format the exceptions, I've created a middleware that will look at the response and reformat the output. It would be great if `exception` property was populated on Response so I could rely on `instanceof OAuthServerException` match, but nope, it's null.

```
namespace App\Http\Middleware;

use Closure;

class TranslateOAuthException
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        // we don't have access to exception property on response, so
        // we have to parse the content
        if ($response->status() == 400) {
            $content = $response->getContent();

            $json = json_decode($content);
            if (!empty($json->error) && in_array($json->error, ['invalid_request', 'invalid_grant']) && !empty($json->message) && !empty($json->hint)) {
                $payload = [
                    'error' => $json->error,
                    'error_description' => $json->message." ".$json->hint
                ];

                $response->setContent(json_encode($payload));
            }
        }

        return $response;
    }
}
```

**Comment by biodunbamigboye** [comment]
I faced this same issue today, and came out with a very simple though not syntactically elegant solution, but it works like magic
Note that my project is running on laravel 8 and might not be able to benefit from most recent fixes 

Inside Handler.php  add League\OAuth2\Server\Exception\OAuthServerException to $dontReport array then in render method, based on the message Log a custom error
`
    use League\OAuth2\Server\Exception\OAuthServerException;

    protected $dontReport = [
        OAuthServerException::class
    ];

    public function render($request, Throwable $exception)
     {
          if ($exception->getMessage() === 'Unauthenticated.') {
            Log::error('error message, it could be json encoded array, string, or any thing you desire'));
            }
     }
`
