### ISSUE TITLE
How to produce shorter access token?

### ISSUE THREAD

**Issue by edmandiesamonte** [laravel/passport#401]
Is there a way to generate shorter access token?

I'm currently building a platform for internet of things and I want to authenticate my low-power low-memory devices. Which also means that every byte count. More than a hundred characters for authentication means bigger memory and bandwidth usage. Also, is there a way to just let my code generate access token so that I can put some prefix to it?

Thanks.

**Comment by ashutoshpw** [comment]
@edmandiesamonte 
I am trying to implement OAuth on my Laravel Application and could successfully generate access tokens, but I am unable to access the logged in user data with that access_token. Can you please help me regarding this?

**Comment by ricardofadini** [comment]
+1
I think that's interesting the possibility to set token length.

**Comment by rcmsjr** [comment]
+1

**Comment by haashenrique** [comment]
Yes, I support this request too.. I think is should be up to the developer to choose this length.

**Comment by alexbilbie** [comment]
In the case of IoT devices I think you actually want CBOR authentication.

Please could you re-open this request as an issue on github.com/thephpleague/oauth2-server ?

**Comment by anbu369** [comment]
I generated a personal access token and the length is 1074 whereas the token stored in database is 80. Is there a way to get a shorter token since I will be giving this to the users for api access and this is too long

**Comment by nestormata** [comment]
One of the things that define the token length is the key length.
One could generate a shorter RSA key and therefore get a shorter token.
An easy way to do this is to create your own passport key command in your project, you could just copy the command from: `vendor/laravel/passport/src/Console/KeysCommand.php`, and then just change the signature to something like "passport:short-key" and change the parameter passed to the createKey method, maybe pass 1024 instead of 4096.

**Comment by nestormata** [comment]
In terms of the passport project, it could be nice to actually accept some parameters in that command to allow the person select some options when creating the key.

**Comment by imagina** [comment]
+1

**Comment by HusDev** [comment]
+1
