### ISSUE TITLE
Can someone verify client credential grants are honoring scopes provided in routes files?

### ISSUE THREAD

**Issue by chadhobson** [laravel/passport#501]
I'm on L5.5 and Passport 4.0. I see the requested scope in the database with the access token I requested. Middleware is working fine with regards to client credentials grant but no matter what I change the scope to, the request always succeeds.

Diving into the CheckClientCredentials middleware, line 65, in the validateScopes() function the $scopes array passed through is always empty meaning no chance of MissingScopeException being fired later on line 74.

Can someone verify I'm not imagining this?

**Comment by chadhobson** [comment]
A little more testing to report. If I pass a valid, unrelated password token on the request to an endpoint protected only by client credential middleware, it still works.

So I think I've proven on my end that scopes are being completely ignored here. Will try to dive deeper and get to the bottom of it.

**Comment by tankerkiller125** [comment]
The scopes middleware is required on the routes otherwise the application can not possibly know what routes the user should and shouldn't be able to access. With only a client credentials middleware I get the same results as you do (which is expected) however with the scopes middleware (as noted in the docs) I get access denied for endpoints that I do not have a scope for.

**Comment by driesvints** [comment]
So the way it works is as follows:

```php
Route::get('/user', function (Request $request) {
    ...
})->middleware('client:scope1,scope2');
```

The docs aren't clear on this and I'll send in something to clarify this behavior.
