### ISSUE TITLE
Ajax authentication issue

### ISSUE THREAD

**Issue by sagarrabadiya** [laravel/passport#52]
CreateFreshApiToken middleware should issue `laravel_token` cookie if post request is coming through ajax, so that one can allow user to login with ajax for ex. vue-resource.

for now because of this i can send authentication data using vue resource to server, but because of issuing token only for get request it's not returning laravel_token cookie so user can not access api correctly if login is done using ajax.

for example
`return $request->isMethod('GET') && $request->user();`

can be
`return ($request->isMethod('GET') || $request->ajax() ) && $request->user();`

**Comment by Townfolio** [comment]
I don't believe your problem lies in how you're posting your data to the server to login. I think it might lay in what you're doing after that login screen. In order for a response to receive a fresh token, it has to meet a few criteria, the first one being what you've shown above.

```
/**
 * Determine if the request should receive a fresh token.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return bool
 */
protected function requestShouldReceiveFreshToken($request)
{
    return $request->isMethod('GET') && $request->user();
}
```

The second one (and I believe this might be tripping you up possibly) is this.

```
/**
 * Determine if the response should receive a fresh token.
 *
 * @param  \Illuminate\Http\Response  $request
 * @return bool
 */
protected function responseShouldReceiveFreshToken($response)
{
    return $response instanceof Response &&
                ! $this->alreadyContainsToken($response);
}
```

That `instanceof Response` means that the response has to be `\Illuminate\Http\Response` and the only way it wouldn't (in my mind) in your app is if you're doing a SPA-like front end where after you login you're doing some front end routing instead of redirecting to a new page from the backend. If that is the case, then you should consider making the login screen separate from the front end routing. 

If that isn't the case, please provide more context so we can figure out a solution for you.

**Comment by sagarrabadiya** [comment]
yeah, i am redirecting user after login using vue route but why is it necessary to keep login age seperate from my spa? its not that good experience as it do full age load

**Comment by Townfolio** [comment]
It's not necessary, but in order to make your app work with Passport and the `CreateFreshApiToken` middleware, you would need to. Passport is expecting the GET response to be an instance of `\Illuminate\Http\Response` in order to attach the cookie, but since you're not logged in at the time of it issuing the only `\Illuminate\Http\Response`, no cookie can ever be issued.

I think the better way for you to be using Passport is by using the [Password Grant Token](https://laravel.com/docs/5.3/passport#password-grant-tokens). That way, you can keep your ajax login and still get an access token and refresh token as a response to the ajax request.

**Comment by sagarrabadiya** [comment]
i have already overridden the CreateFreshApiToken middleware with above code and its working correctly, so you can close the issue, if the issue seems invalid.. :)

but using password grant token, i think i am creating one additional token which is not required for my own application usage, because consider if user refresh the page, then it will have larave_token cookie so password grant token becomes unnecessary.

**Comment by Townfolio** [comment]
You are correct, it would create a token assuming you do log them in using the auth facilities. If you only get a token, then they wouldn't be "logged in" on the server, they would just have the ability to access the API using a (probably) locally stored access token and refresh token.

Either way, fair enough, I just wasn't sure this was a wide use case, but if it is, I'm sure it could be looked at again in the future :)

**Comment by sagarrabadiya** [comment]
so may be we can keep this open for @taylorotwell to look into.. :)

**Comment by themsaid** [comment]
Closing since there's no plan for this change at the moment.
