### ISSUE TITLE
Personal Token by Query Paramater

### ISSUE THREAD

**Issue by poxin13** [laravel/passport#56]
Is there a way to do this with the current code if I request input of a parameter and pass it something like `passport.dev?token=personalToken` ?

I couldn't figure out how to check if a token is valid or not, was going to implement a custom middleware for this. I have an old intranet app that doesn't work very well passing Header information for the documented Authorization Bearer method.

**Comment by Townfolio** [comment]
Currently, the only way in Passport to pass your access token is through the Authorization header. Passing it through the query string is [extremely dangerous](http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html#query-param).

When using Passport as your guard, this is how you it checks for an authenticated user.

```
/**
 * Get the user for the incoming request.
 *
 * @param  Request  $request
 * @return mixed
 */
public function user(Request $request)
{
    if ($request->bearerToken()) {
        return $this->authenticateViaBearerToken($request);
    } elseif ($request->cookie('laravel_token')) {
        return $this->authenticateViaCookie($request);
    }
}
```

So bearer token explicitly checks for the authorization header, but the cookie method simply looks for the `laravel_token` cookie to be present during the request. The [CreateFreshApiToken method](https://laravel.com/docs/5.3/passport#consuming-your-api-with-javascript) sounds like it might work for you since you don't need to pass headers, just a simple cookie which the browser should handle automatically assuming your javascript doesn't have any problems.

That being said, that method also relies on how your intranet is setup and whether or not you have a "domain" which a cookie can be attached to.

**Comment by poxin13** [comment]
I do agree that it's dangerous and went ahead skipping that function completely in my project. I appreciate the information regarding the cookie, that may prove useful in the future. Went ahead and did a more regular method of authorization from the intranet app.
