### ISSUE TITLE
String after a valid client id throws sql error

### ISSUE THREAD

**Issue by anantab** [laravel/passport#581]
I made a typo and sent '1w' instead of 1 for client_id parameter, when calling "oauth/token" route to get passport grant token.

```
POST http://127.0.0.1:8000/oauth/token
{
	"grant_type":"password",
        "client_id" : "1w",
        "client_secret" : "my-client-secret",
        "username" : "my@email.com",
        "password" : "mypassword",
        "scope" : "*"
}
```

and got sql error below. 
```
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'client_id' at row 1 (SQL: insert into `oauth_access_tokens` (`id`, `user_id`, `client_id`, `scopes`, `revoked`, `created_at`, `updated_at`, `expires_at`) values
```

The issue seems to be when id obtained after parsing the client_id parameter to integer existed in database.

That is, if there is client with id 2 in database and if I sent client_id as  '2randomalphabets', then I get error but if there is no client with id 2 i get "Client authentication failed" message back.

**Comment by driesvints** [comment]
I don't really get how this is an issue. Just pass along the correct id?

**Comment by anantab** [comment]
> I don't really get how this is an issue. Just pass along the correct id?

Or probably handle the input correctly and return proper error response than raw sql error?

**Comment by lloricode** [comment]
same here, is there an any exception to handle it ?

**Comment by driesvints** [comment]
I looked into this but the way I see it is that the best place to throw a dedicated exception is in the `issueAuthCode` method of the `AbstractGrant` class. Unfortunately this is in the oauth2 library so it would have to be done there. I think an exception right after the first catch would do. Something like `CannotIssueAccessToken` or something.

What do you think @sephster?

**Comment by Sephster** [comment]
It is a tricky one as the league's package is trying to be agnostic with regard to a db backend. Would it be possible to add some validation on the route to check if the client ID contains non-numeric characters? If so I think that might be an easier option as Passports implementation will always have integers.

Also as this is a warning, does the code continue regardless or does this cause a critical failure?

**Comment by Sephster** [comment]
It looks like there is an issue with the docblock declaration there. It probably should be mixed rather than string. It seems we have a mix of both between the interface and the trait so I've raised an issue to fix this. Thanks for pointing it out.

WRT the UUID, I hadn't even thought of that but yeah, it would break their implementation. Would it be possible to let users define their own validation? Could be something to consider.

The other thing worth noting here I guess is that this situation should be very unlikely in a production system. The original poster has admitted it is a typo that caused this error but in a production system, the client should be some kind of application which should eliminate this risk.

In the meantime, I will look at seeing if we can add in a general exception as you suggested when issuing an AuthCode as the Unique Token Identifier validation rule doesn't cut it for this instance. Thanks for the suggestion!

**Comment by driesvints** [comment]
@Sephster thanks for helping looking into this! Going to close this off then because it's in meantime

> Would it be possible to let users define their own validation?

Sure thing, they can already do this by overwriting the controller method. I think it would be overkill to provide some kind of abstraction layer for it.

**Comment by Sephster** [comment]
Sounds good. I will create an issue this evening and give you a prompt or submit a PR once this has been added in. Cheers @driesvints

**Comment by mihailivanchev** [comment]
Hello,
I have encountered the same problem. 
When trying to generate an oauth token, I am testing with a request that sends a client_id that looks like this:
`10,0)waitfor delay'0:0:20'--`. I have an oauth client with id = 10. For some reason this string is able to "fool" the existing logic and by debugging the code, I see that in the ClientRepository, the find method actually is able to find the client with id=10 and returns it!
This is very odd by itself, but the bigger question is why is Passport working with the user provided client_id in the request, when it was able to find a client? Why not use the client coming from the DB?
If Passport uses the id of the client it found in the DB, there won't be an issue. 
The problem comes from Passport trying to write the erroneous client_id (provided in the client request) in the oauth_acces_token table. Switching from client input to what comes from the DB should negate the problem.
We should not rely on user provided data and try to save that in the DB without proper validation.
