### ISSUE TITLE
How can I disable the refresh token feature?

### ISSUE THREAD

**Issue by itzikbenh** [laravel/passport#588]
I'm renewing the access_token on each request, so I don't really need a refresh_token. Plus it adds a security concern for me. How would you disable it?

**Comment by tankerkiller125** [comment]
It sounds like what your currently doing would be something better done by the implicit grant rather than a standard grant. Refresh tokens allow clients to cache the token until they expire and the refresh token allows the client to get a new token without the user re-authenticating the application.

An implicit grant does not have this caching or refresh token nature because it is designed to change on every request.

**Comment by emparker** [comment]
I came across this same issue. My main concern is the security where refresh token can be stolen from browser. Since using refresh token also returns new refresh token, this could end up in really bad situation. Even though it is recommended to use Implicit or authorization code flow for browser app, I just wanted to avoid redirect to the api server to login since I am using single page app. Also, api server is stateless and have to configure and setup session just for the login.

So, my workaround is to set the same expiry date for both access token and refresh token.

```
       $expireAt = now()->addDays(7);
        Passport::tokensExpireIn($expireAt);
        Passport::refreshTokensExpireIn($expireAt);
```

Not sure if there is a better way. It would be nice to be able to disable a particular client from getting refresh token :-D

**Comment by Sephster** [comment]
You shouldn't renew the access token on each request. There is little point to this. Just make your access token long lived. The OAuth server doesn't _have_ to issue a refresh token. It is up to the implementer although I'm not sure if there is an option to disable this in Passport. It would be a good feature if not.

@emparker if you cannot keep access tokens/secrets secret e.g. in an SPA where JavaScript is primarily used, you should be using the Implicit Grant which does _not_ return a refresh token as the client has no means of keeping it secret. See [Alex Bilbie's blog](https://alexbilbie.com/guide-to-oauth-2-grants/) for more information on which grants you should be using.

**Comment by driesvints** [comment]
I think that indeed an Implicit Grant would work best here. I personally doubt that we'd ever make refresh tokens configurable.
