### ISSUE TITLE
使用另外一个guard

### ISSUE THREAD

**Issue by UniYL** [laravel/passport#603]
当guard为user_g，无法使用middleware => auth:user_g。
因为这个地方写成静态了。
`/**`
`     * Register the routes needed for managing clients.`
`     *`
`     * @return void`
`     */`
`    public function forClients()`
`    {`
`        $this->router->group(['middleware' => ['web', 'auth']], function ($router) {`
`            $router->get('/clients', [`
`                'uses' => 'ClientController@forUser',`
`            ]);`

`            $router->post('/clients', [`
`                'uses' => 'ClientController@store',`
`            ]);`

`            $router->put('/clients/{client_id}', [`
`                'uses' => 'ClientController@update',`
`            ]);`

`            $router->delete('/clients/{client_id}', [`
`                'uses' => 'ClientController@destroy',`
`            ]);`
`        });`
`    }`

**Comment by UniYL** [comment]
@carusogabriel sorry,I Do not speak English. ——https://translate.google.cn

**Comment by yuyenkan** [comment]
Translating.......

当guard为user_g，无法使用middleware => auth:user_g。
因为这个地方写成静态了。

--------------------------------------------

when $guard is user_g, unable to use ["middleware" => "auth:user_g"] in route
because it is static


/**
* Register the routes needed for managing clients.
*
* @return void
*/
public function forClients()
{
$this->router->group(['middleware' => ['web', 'auth']], function ($router) {
$router->get('/clients', [
'uses' => 'ClientController@forUser',
]);

$router->post('/clients', [
'uses' => 'ClientController@store',
]);

$router->put('/clients/{client_id}', [
'uses' => 'ClientController@update',
]);

$router->delete('/clients/{client_id}', [
'uses' => 'ClientController@destroy',
]);
});
}

**Comment by yuyenkan** [comment]
试试这个

```
Route::group(["middleware" => "auth:user_g"], function(){
     Route::get("/", "Controller@index"); //Sample route
});
```

**Comment by UniYL** [comment]
@yuyenkan 谢谢了。但是这并不是我想要的。原因是在passport包的路由已经写了固定的，请查看passport类。我在想，是否应该自己写路由。

**Comment by yuyenkan** [comment]
@UniYL 会吗？我觉得还好？你想要做成怎样的？

**Comment by driesvints** [comment]
Heya, I'm very sorry but can you please open an issue in English? We can only offer English support I'm afraid because we don't speak Chinese ourselves. Sorry about that.
