### ISSUE TITLE
Always response 401 (Unauthorized) for my Laravel Passport generated OAuth 2 token

### ISSUE THREAD

**Issue by megusta420** [laravel/passport#636]
I am using:

Postman/Insomnia for REST checking
Laravel 5.6 with Laravel Passport
Vagrant (Apache 2, PHP 7.2)
Made all checklist described on Laravel Docs for Laravel Passport and after certain steps I receive HTTP 401 for my valid OAuth access token.

Requested by /oauth/token/ the new access token with client_id and client_secret.
Used received access token to authorize my simple Laravel REST test controller with included Oauth api middleware.
The end is one: 401 unauthorized :(
So, here is some of my configurations:

Apache 
![image](https://user-images.githubusercontent.com/28196153/36109169-5af5d9aa-1027-11e8-8ef4-a5337ffdfea2.png)

api route 
![image](https://user-images.githubusercontent.com/28196153/36109203-666d78ba-1027-11e8-9e09-b67b242550ac.png)

Kernel.php 
![image](https://user-images.githubusercontent.com/28196153/36109222-70e1fbcc-1027-11e8-9484-801e46d14942.png)

PassportServiceProvider.php 
![image](https://user-images.githubusercontent.com/28196153/36109238-7ca71eba-1027-11e8-9359-7a14cf268df8.png)

AuthServiceProvider.php
![image](https://user-images.githubusercontent.com/28196153/36109255-87c36056-1027-11e8-8c11-2e33523e381d.png)

**Comment by andrewmclagan** [comment]
Can you post the request you are issuing to obtain your token, im sure that is where your issue is. You can t use a token that is issued incorrectly.

**Comment by joshharington** [comment]
@andrewmclagan I am getting this issue with Laravel 5.6 now as well. I have had it since Laravel 5.3 where I can get the token just fine, but trying to use the token to access a link that uses `auth:api` always returns `401 unathenticated`. I always resort to using another package as I have tried everything suggested online and nothing ever works for me to solve the problem.

**Comment by andrewmclagan** [comment]
As I stated above, we need to see the request you are making to obtain a token. 

This is not a forum for “how to use passport” it’s for issue tracking. Logging an issue on an issue tracker you do the following:

* List the versions of packages 
* give a replicatable  scenario and even better a git repo with a replicatable issue
* example requests of your entire auth workflow

Questions like you posed “why do I get 401, here are Some code screenshots” is basically asking us to do your work for you. We are not your co-workers. Stackoverflow is used for these userland issues.

But since you asked:

Clear your cache, clear your config, clear the database, reinstall.

**Comment by prasad-thinkbar** [comment]
sd

**Comment by alimc160** [comment]
![image](https://user-images.githubusercontent.com/50473558/57567470-38e09400-73f3-11e9-9379-5cd744058d2b.png)
I am facing this error while login with social media
