### ISSUE TITLE
GET /oauth/clients return 401 Unauthorized

### ISSUE THREAD

**Issue by vadim-givola** [laravel/passport#794]
I can't figure out why GET `/oauth/clients` always return 401 Unauthorized.
Do I need to send any params there?

I'm using Laravel 5.5 and Passport 4.0.3
I tried to make a test with a Postman, but got the same 401 error.

Any ideas what I'm doing wrong?

**Comment by dydzm** [comment]
working on "laravel/framework": "5.5.40"

**Comment by simondavies** [comment]
Since the security update the other day the it breaks.

There is a new update created today / yesterday to fix this.  

But if you run composer update but still nothing like i did I had to target the updated branch directly.

`composer require laravel/passport:4.0.x-dev`

As currently as of today composer update is not picking up the fix yesterday.

This fixed my issue

You can temporarily fix it by adding the following to `App\Http\Middleware\EncryptCookies`

`protected static $serialize = true;`

regarding: https://laravel.com/docs/5.5/upgrade

**Comment by driesvints** [comment]
Please upgrade to the latest version of Passport. See the passport section on https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30
