### ISSUE TITLE
Laravel passport does not see the token, causing "unauthenticated" message

### ISSUE THREAD

**Issue by mfgabriel92** [laravel/passport#807]
Suddenly my application stopped working when trying to access endpoints protected by `auth:api` middleware in the Laravel 5.6.35 back-end using Passport 7.0.1. I've been using it for two weeks but today, after a database refresh, it decided to stop working.

The issue is that it is generating when I register and log-in.

    return Response::json([
        'token' => $user->createToken('foobar')->accessToken,
        'user' => $user
    ], HTTPResponse::$HTTP_OK);

Insomnia rest will then show the following when accessing the routes belonging to the `auth:api` middleware.

> "message": "Unauthenticated."

It was working until an hour ago, and it stopped after I refreshed the database. I dropped and created a new one, registered a test user and attempted to access and endpoint passing the token as `Bearer` token and Accept header to `application/json`.

I don't know how to solve it. I saw where it was failing in `TokenGuard.php` file, but what to do? Why has it suddenly stopped?

**Comment by DanielSteadfast** [comment]
Having the same issue.

**Comment by judahnator** [comment]
Same issue here. Application that has been working for months suddenly stopped working.

I switched from version 6.0.7 to the 7.0 branch and it seems to be working again. Not sure what the deal was, but hopefully this works for you folks.

**Comment by DanielSteadfast** [comment]
I have also just moved to the 7.0 branch and it also appears to be working again now.

**Comment by enkay** [comment]
Upgrading Passport to 7.0 fixed the requests in the app, but actingAs in the tests still returns 403. Anyone else experience this issue?

**Comment by acacha** [comment]
My experience with Laravel Passport: 401 "unauthenticated" error could be so many thinks because 401 errors are thrown when an exception occurs but you could not see the specific error exception. 

In this cases try to debug the error at Laravel\Passport\Guards\TokenGuard class debugging methods authenticateViaBearerToken or authenticateViaCookie (depending what you use). Here you wolud see try/catchs that "swallow" exception errors so put here a dd or something similar to know which error do you have.

**Comment by driesvints** [comment]
Try to update to the latest Passport version and let me know if the problem still occurs then.
