### ISSUE TITLE
Passport works fine on PostMan, but returns 401 inside the app?

### ISSUE THREAD

**Issue by NeekPizza** [laravel/passport#810]
Laravel/React/Valet

I have a route that needs a token. When I make my Axios call inside of the react app, it returns 401. However, when I grab the parsed header inside of the Network tab it shows "Bearer ${correctToken}".

I grab that entire string, "Bearer ${token}" and throw it into PostMan and I get the correct object, no 401.

I have tried all the fixes and am now on page 3 of google, the dark abyss. Please help.

**Comment by mementomori-jp** [comment]
How about update version to 7.0 ?

**Comment by NeekPizza** [comment]
already on 7.0

**Comment by jake142** [comment]
I got the same issue after composer update. Running the token in my session (CreateFreshApiToken) with axios I get 401 but I can run it in Insomnia.

It works in:

"name": "laravel/passport",
"version": "v6.0.7",

**Comment by NeekPizza** [comment]
@jake142 downgrading should never be the fix unless the team has released bad code...regardless, it still didnt work.

**Comment by ajthenewguy** [comment]
Be sure to add Passport::withoutCookieSerialization() to AppServiceProvider, as mentioned in the [upgrade guide](https://laravel.com/docs/5.6/upgrade).

**Comment by jake142** [comment]
Aaah, thank you! Solved my issue.

**Comment by xutl** [comment]
add `Passport::$ignoreCsrfToken = true;` to AuthServiceProvider.php file

**Comment by driesvints** [comment]
@NeekPizza Please provide more info: responses from your api, headers, routes you're calling, JS you're using to call your API.

**Comment by walheredia** [comment]
@jake142 is there any possibility you can add some code you have done for helping us to solve the issue?

**Comment by jake142** [comment]
Sure, I followed the instructions in the [upgrade guide](https://laravel.com/docs/5.6/upgrade) and added Laravel\Passport\Passport::withoutCookieSerialization() in my AppServiceProvider boot method.

**Comment by walheredia** [comment]
I'd like to add info in case it is useful for other people. I have fixed the issue that is related to this.
I am working in Angular 7, and Laravel 5.7 as API REST. In angular I created an interceptor in order to add the headers 'automatically'. 
And then, I've created the API for private routes and also experienced these issues described above.
POSTMAN and Advanced REST worked well, the problem were the requests by Angular. 
And now, I've added the headers manually in each HTTP request as follows;

//Example for 'GET' request
userLogOut(): Observable<any[]> {
    let parameters = new HttpHeaders();
    parameters = parameters.set('Authorization', "Bearer " + this.session.getToken());
    return this.http.get<any[]>(this.usersUrl + 'logout', { headers: parameters });
}

//Example for 'POST' request
userLogOut(): Observable<any[]> {
    let parameters = new HttpHeaders();
    parameters = parameters.set('Authorization', "Bearer " + this.session.getToken() );
    return this.http.post<any[]>(this.usersUrl + 'logout', '', { headers: parameters } );
}

Both of them work well.
Don't forget to add this "private http: HttpClient" at your constructor and "import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';"

Hope it helps!
