### ISSUE TITLE
Passport - create password client

### ISSUE THREAD

**Issue by xorock** [laravel/passport#814]
Currently there is no way to create password client with vue component.
Also, both ClientController store and update methods (lines 67 and 92) do not allow optional parameters. Is there a specific reason why it was written this way?

**Comment by driesvints** [comment]
Hey @xorock. This is because Password Grant Tokens are meant for 1st party clients like the mobile app of your web app. This allows users to login and let your own mobile app consume your api.

Clients created by users are meant for 3rd party clients which use those clients to consume apis which are limited in usage to the client's resources.

Take Github for an example. They probably have a passport client so their mobile app (if they have one) allows users to login to their account and control the data they see on Github. But they also allow their users to create clients which issue access tokens so those developers can use it to make use of Github features (https://github.com/settings/developers). 

Hope this explanation helps :)

**Comment by xorock** [comment]
@driesvints Do not get me wrong, but I fully understand what password tokens are for and are deliberately used in the project. Our API is used to communicate with the related company (sub-company) and it has an access to panel in which it can add its own tokens for internal purposes. Temporarily, a trigger has been created that changes the flag before writing but it's really weird that there is no other option without rewriting the whole component.

**Comment by driesvints** [comment]
It's because of the reasons I explained above: access token grant clients are for third party apps (your customers) and password grant clients are for your own first party apps. That's why the components don't allow you to create password grant clients. They're meant to give you some scaffolding to get you started with a way for your customers to create access token grant clients.
