### ISSUE TITLE
Is it possible/acceptable to use the same client for multiple grant types?

### ISSUE THREAD

**Issue by owenconti** [laravel/passport#922]
Looks like the `handlesGrant` method of `ClientRepository` is preventing a Client from being an Authorization Code Grant client and a Personal Access Token Grant client

Is there a specific reason for this? Is it against the OAuth spec?

**Comment by Sephster** [comment]
This is not against the OAuth2 spec.

**Comment by driesvints** [comment]
So we should be allowing it? Is that even possible with the current DB scheme?

**Comment by Sephster** [comment]
Sorry for the confusion caused. While there aren't any restrictions it does seem odd to go down this route.

It might be possible with the current scheme. The switch in `handlesGrant()` seems to dictate this so I think in theory, it should be possible.

It would be good to find out what the use case is from @owenconti - the OAuth 2 spec doesn't restrict a client from using multiple grants but it is unusual.

The client will typically choose which grant to use based on a number of factors such as:

* can they keep a secret
* is the client first or third party?
* who will own the access token?

It would be strange for the client to be both first and third party, or sometimes confidential and sometimes public which is why the client to grant type one-to-one relationship makes sense to me here.

There could perhaps be a use case where you have a client that has a PHP web app and a JS mobile app which would use different grants but I would advocate that these should be treated as separate clients for simplicity's sake.

This is largely an implementation policy decision. I would lean towards leaving things as is unless a good use case is presented to change this.

**Comment by owenconti** [comment]
I was a bit confused because the DB schema uses booleans for `personal_access_client` and `password_access_client`, which means a single client can grant Personal Access Tokens and Password Access Tokens at the same time. However, because they can grant those tokens, they cannot grant Authorisation Tokens. I just wasn't clear why that was the case, or if it was a bug.

My primary use case is I want my app to issue Personal Access Tokens to my users to use with my front end (users would not be able to issue their own Personal Access Tokens). I was using `CreateFreshApiToken` to deal with this, but the `CreateFreshApiToken` does not support scopes, so I had to switch to Personal Access Tokens.

The secondary use case was to make things a bit simpler by not requiring multiple clients for different grant types.

I wasn't sure if I was overlooking something, or just don't understand why separate clients are recommended.

**Comment by driesvints** [comment]
Okay no worries. I agree with @Sephster that it might be best to leave things as is and that you create separate clients.
